# Generated by Django 4.2.16 on 2024-11-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='coins',
        ),
        migrations.AddField(
            model_name='users',
            name='favorite_coins_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='favorite coins'),
        ),
    ]
