# Generated by Django 4.2.16 on 2024-12-08 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_email_verified_users_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='users',
            name='verification_code',
        ),
    ]
