# Generated by Django 4.2.16 on 2024-12-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_temporaryregistration_remove_users_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='favorite_coins_id',
            field=models.JSONField(blank=True, default=list, verbose_name='favorite coins'),
        ),
    ]
