# Generated by Django 4.2.16 on 2024-12-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_favorite_coins_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryRegistration',
        ),
    ]
