# Generated by Django 4.2.16 on 2024-10-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/coinIcons', verbose_name='image')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Symbol')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'coin',
                'verbose_name_plural': 'coins',
                'db_table': 'coins',
                'ordering': ('symbol',),
            },
        ),
    ]
