# Generated by Django 4.2.16 on 2024-10-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coins_images')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Symbol')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change', models.CharField(blank=True, max_length=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cap', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'coin',
                'verbose_name_plural': 'coins',
                'db_table': 'coins',
            },
        ),
    ]
