# Generated by Django 4.2.16 on 2024-11-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='image',
            field=models.CharField(blank=True, null=True, verbose_name='image'),
        ),
    ]
