# Generated by Django 4.2.16 on 2024-11-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_coins_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
