# Generated by Django 4.2.16 on 2024-12-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_market_remove_coins_market_coins_market_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coins',
            name='market_id',
        ),
        migrations.AddField(
            model_name='coins',
            name='markets',
            field=models.ManyToManyField(blank=True, related_name='coins', to='coins.market', verbose_name='Markets'),
        ),
    ]
