# Generated by Django 4.2.16 on 2024-12-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_remove_coins_market_id_coins_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='market_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Market ID'),
        ),
    ]
